In [33]:
import torch
from torch.optim import Adam, SGD

In [2]:
a = torch.ones((5,5)).requires_grad_(True)
adam = Adam([a], 0.1)

In [3]:
adam.param_groups

[{'params': [tensor([[1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.]], requires_grad=True)],
  'lr': 0.1,
  'betas': (0.9, 0.999),
  'eps': 1e-08,
  'weight_decay': 0,
  'amsgrad': False,
  'maximize': False,
  'foreach': None,
  'capturable': False}]

In [4]:
b = torch.zeros((2,2)).requires_grad_(True)
c = torch.zeros((2,2)).requires_grad_(True)
adam.add_param_group({'params': [b, c], 'lr': 0.001})

In [5]:
adam.param_groups

[{'params': [tensor([[1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.]], requires_grad=True)],
  'lr': 0.1,
  'betas': (0.9, 0.999),
  'eps': 1e-08,
  'weight_decay': 0,
  'amsgrad': False,
  'maximize': False,
  'foreach': None,
  'capturable': False},
 {'params': [tensor([[0., 0.],
           [0., 0.]], requires_grad=True),
   tensor([[0., 0.],
           [0., 0.]], requires_grad=True)],
  'lr': 0.001,
  'betas': (0.9, 0.999),
  'eps': 1e-08,
  'weight_decay': 0,
  'amsgrad': False,
  'maximize': False,
  'foreach': None,
  'capturable': False}]

In [8]:
b[0][0]=100

RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation.

In [9]:
c = b.to('cpu')
c.is_leaf

True

In [10]:
import copy
copygroup = copy.deepcopy(adam.param_groups)

In [11]:
copygroup

[{'params': [tensor([[1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.]], requires_grad=True)],
  'lr': 0.1,
  'betas': (0.9, 0.999),
  'eps': 1e-08,
  'weight_decay': 0,
  'amsgrad': False,
  'maximize': False,
  'foreach': None,
  'capturable': False},
 {'params': [tensor([[0., 0.],
           [0., 0.]], requires_grad=True)],
  'lr': 0.001,
  'betas': (0.9, 0.999),
  'eps': 1e-08,
  'weight_decay': 0,
  'amsgrad': False,
  'maximize': False,
  'foreach': None,
  'capturable': False}]

In [14]:
with torch.no_grad():
    copygroup[0]['params'][0].add_(5)
copygroup

[{'params': [tensor([[11., 11., 11., 11., 11.],
           [11., 11., 11., 11., 11.],
           [11., 11., 11., 11., 11.],
           [11., 11., 11., 11., 11.],
           [11., 11., 11., 11., 11.]], requires_grad=True)],
  'lr': 0.1,
  'betas': (0.9, 0.999),
  'eps': 1e-08,
  'weight_decay': 0,
  'amsgrad': False,
  'maximize': False,
  'foreach': None,
  'capturable': False},
 {'params': [tensor([[0., 0.],
           [0., 0.]], requires_grad=True)],
  'lr': 0.001,
  'betas': (0.9, 0.999),
  'eps': 1e-08,
  'weight_decay': 0,
  'amsgrad': False,
  'maximize': False,
  'foreach': None,
  'capturable': False}]

In [15]:
adam.param_groups

[{'params': [tensor([[1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.]], requires_grad=True)],
  'lr': 0.1,
  'betas': (0.9, 0.999),
  'eps': 1e-08,
  'weight_decay': 0,
  'amsgrad': False,
  'maximize': False,
  'foreach': None,
  'capturable': False},
 {'params': [tensor([[0., 0.],
           [0., 0.]], requires_grad=True)],
  'lr': 0.001,
  'betas': (0.9, 0.999),
  'eps': 1e-08,
  'weight_decay': 0,
  'amsgrad': False,
  'maximize': False,
  'foreach': None,
  'capturable': False}]

In [16]:
with torch.no_grad():
    adam.param_groups[0]['params'][0][0]=100

In [9]:
a.grad = torch.ones_like(a)
b.grad = torch.ones_like(b)
c.grad = torch.ones_like(c)
adam.step()

In [19]:
adam.param_groups

[{'params': [tensor([[99.9000, 99.9000, 99.9000, 99.9000, 99.9000],
           [ 0.9000,  0.9000,  0.9000,  0.9000,  0.9000],
           [ 0.9000,  0.9000,  0.9000,  0.9000,  0.9000],
           [ 0.9000,  0.9000,  0.9000,  0.9000,  0.9000],
           [ 0.9000,  0.9000,  0.9000,  0.9000,  0.9000]], requires_grad=True)],
  'lr': 0.1,
  'betas': (0.9, 0.999),
  'eps': 1e-08,
  'weight_decay': 0,
  'amsgrad': False,
  'maximize': False,
  'foreach': None,
  'capturable': False},
 {'params': [tensor([[-0.0010, -0.0010],
           [-0.0010, -0.0010]], requires_grad=True)],
  'lr': 0.001,
  'betas': (0.9, 0.999),
  'eps': 1e-08,
  'weight_decay': 0,
  'amsgrad': False,
  'maximize': False,
  'foreach': None,
  'capturable': False}]

In [10]:
adam.state

defaultdict(dict,
            {tensor([[0.8000, 0.8000, 0.8000, 0.8000, 0.8000],
                     [0.8000, 0.8000, 0.8000, 0.8000, 0.8000],
                     [0.8000, 0.8000, 0.8000, 0.8000, 0.8000],
                     [0.8000, 0.8000, 0.8000, 0.8000, 0.8000],
                     [0.8000, 0.8000, 0.8000, 0.8000, 0.8000]], requires_grad=True): {'step': tensor(2.),
              'exp_avg': tensor([[0.1900, 0.1900, 0.1900, 0.1900, 0.1900],
                      [0.1900, 0.1900, 0.1900, 0.1900, 0.1900],
                      [0.1900, 0.1900, 0.1900, 0.1900, 0.1900],
                      [0.1900, 0.1900, 0.1900, 0.1900, 0.1900],
                      [0.1900, 0.1900, 0.1900, 0.1900, 0.1900]]),
              'exp_avg_sq': tensor([[0.0020, 0.0020, 0.0020, 0.0020, 0.0020],
                      [0.0020, 0.0020, 0.0020, 0.0020, 0.0020],
                      [0.0020, 0.0020, 0.0020, 0.0020, 0.0020],
                      [0.0020, 0.0020, 0.0020, 0.0020, 0.0020],
                     

In [21]:
adam.defaults

{'lr': 0.1,
 'betas': (0.9, 0.999),
 'eps': 1e-08,
 'weight_decay': 0,
 'amsgrad': False,
 'maximize': False,
 'foreach': None,
 'capturable': False}

In [22]:
adam.param_groups

[{'params': [tensor([[99.9000, 99.9000, 99.9000, 99.9000, 99.9000],
           [ 0.9000,  0.9000,  0.9000,  0.9000,  0.9000],
           [ 0.9000,  0.9000,  0.9000,  0.9000,  0.9000],
           [ 0.9000,  0.9000,  0.9000,  0.9000,  0.9000],
           [ 0.9000,  0.9000,  0.9000,  0.9000,  0.9000]], requires_grad=True)],
  'lr': 0.1,
  'betas': (0.9, 0.999),
  'eps': 1e-08,
  'weight_decay': 0,
  'amsgrad': False,
  'maximize': False,
  'foreach': None,
  'capturable': False},
 {'params': [tensor([[-0.0010, -0.0010],
           [-0.0010, -0.0010]], requires_grad=True)],
  'lr': 0.001,
  'betas': (0.9, 0.999),
  'eps': 1e-08,
  'weight_decay': 0,
  'amsgrad': False,
  'maximize': False,
  'foreach': None,
  'capturable': False}]

In [29]:
def boo(a, *args, b=1, **kwargs):
    print('a:', a)
    print('b', b)
    print('args:', args)
    print('kwargs', kwargs)

boo(1)
    

a: 1
b 1
args: ()
kwargs {}


In [11]:
a.detach().requires_grad

False

In [12]:
sgd = torch.optim.SGD([a], 0.01)
a.grad = torch.zeros_like(a)
sgd.step()
sgd.state

defaultdict(dict,
            {tensor([[0.8000, 0.8000, 0.8000, 0.8000, 0.8000],
                     [0.8000, 0.8000, 0.8000, 0.8000, 0.8000],
                     [0.8000, 0.8000, 0.8000, 0.8000, 0.8000],
                     [0.8000, 0.8000, 0.8000, 0.8000, 0.8000],
                     [0.8000, 0.8000, 0.8000, 0.8000, 0.8000]], requires_grad=True): {'momentum_buffer': None}})

In [14]:
a = torch.ones((5,5)).requires_grad_()
a.grad = torch.zeros_like(a)

In [15]:
a.grad = torch.zeros_like(a).requires_grad_()

In [17]:
a.grad.grad

In [19]:
with torch.no_grad():
    a.grad.add_(torch.ones_like(a))

In [20]:
a.grad

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], requires_grad=True)

In [21]:
torch.ones_like(a).requires_grad

False

In [24]:
import numpy as np
np.power(4, 0.4)

1.7411011265922482

In [27]:
a = torch.ones(5)
b = torch.ones(10)
c = torch.cat([a,b])
d = c
del c
print(a)
print(b)
print(d)

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [28]:
d[0]=100
print(a,b)

tensor([1., 1., 1., 1., 1.]) tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [29]:
e = a.div_(2)
print(a,e)
print(a is e)

tensor([0.5000, 0.5000, 0.5000, 0.5000, 0.5000]) tensor([0.5000, 0.5000, 0.5000, 0.5000, 0.5000])
True


In [32]:
boo = []
boo[2:]

[]

In [36]:
sgd = SGD([a], 0.1)
sgd.param_groups

[{'params': [tensor([0.5000, 0.5000, 0.5000, 0.5000, 0.5000])],
  'lr': 0.1,
  'momentum': 0,
  'dampening': 0,
  'weight_decay': 0,
  'nesterov': False,
  'maximize': False,
  'foreach': None}]

In [3]:
import numpy as np
import torch



In [4]:
torch.rand(5)

tensor([0.1514, 0.6722, 0.9289, 0.0459, 0.0094])

In [10]:
torch.from_numpy(np.random.uniform(0,1, (10,1,1)))

tensor([[[0.7066]],

        [[0.2878]],

        [[0.5519]],

        [[0.0588]],

        [[0.3506]],

        [[0.0727]],

        [[0.7503]],

        [[0.5174]],

        [[0.3404]],

        [[0.8765]]], dtype=torch.float64)

In [12]:
a = torch.ones(5)
a[[0,2,3]]

tensor([1., 1., 1.])

In [13]:
a.__getitem__([0,2,3])

tensor([1., 1., 1.])

In [15]:
torch.repeat_interleave(torch.arange(10), 2, dim=0)

tensor([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9])

In [17]:
torch.argmax(torch.tensor([[1,2,3],[2,3,4]]), dim=1)

tensor([2, 2])

In [31]:
torch.ones((5,2))[torch.tensor([False, False, False, False, True])].shape

torch.Size([1, 2])

In [23]:
sum(torch.tensor([False, False, True, True, True]))

tensor(3)

In [26]:
all([True, True, False])

False

In [34]:
aug = lambda x: x
aug([5], [6])

TypeError: <lambda>() takes 1 positional argument but 2 were given

In [38]:
from torch.utils.data import DataLoader

loader = DataLoader(torch.arange(100))

In [39]:
litr = iter(loader)

In [41]:
next(litr)

tensor([1])

In [43]:
torch.eq(torch.ones(5), torch.ones(5))

tensor([True, True, True, True, True])

In [49]:
torch.argmax(torch.tensor([[2,3,4], [3,2,4]]), dim=1).to(dtype=torch.long)

tensor([2, 2])

In [50]:
torch.long

torch.int64

In [53]:
torch.nn.functional.one_hot(torch.arange(10))

tensor([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [54]:
a = torch.ones(10).requires_grad_()

In [58]:
loss = torch.sum(a[:5])
grads = torch.autograd.grad(loss, [a])
a.grad = grads[0]
a.grad

tensor([1., 1., 1., 1., 1., 0., 0., 0., 0., 0.])

In [62]:
import numpy as np

def rdnum():
    print(np.random.uniform())

def setseed():
    np.random.seed(0)


for i in range(10):
    setseed()
    rdnum()



0.5488135039273248
0.5488135039273248
0.5488135039273248
0.5488135039273248
0.5488135039273248
0.5488135039273248
0.5488135039273248
0.5488135039273248
0.5488135039273248
0.5488135039273248
